import { theme } from 'antd'
import type { ThemeConfig } from 'antd'

/**
 * 中性经典暗色色板：灰阶负责界面层级，颜色只承担交互和业务语义。
 * AntD 与业务 CSS 均从这里取值，避免两套主题常量漂移。
 */
export const darkPalette = {
  canvas: '#141414',
  surfaceUnder: '#101010',
  surfaceSubtle: '#181818',
  surface: '#1f1f1f',
  surfaceRaised: '#262626',
  borderSubtle: '#2b2b2b',
  border: '#3c3c3c',
  text: '#e6e6e6',
  textSecondary: '#b3b3b3',
  textTertiary: '#8f8f8f',
  textOnAccent: '#ffffff',
  textOnSuccess: '#06251d',
  primary: '#0078d4',
  primaryHover: '#026ec1',
  primaryActive: '#005fb8',
  primaryText: '#4daafc',
  primarySoft: 'rgba(0, 120, 212, 0.16)',
  success: '#3fb950',
  successSoft: 'rgba(63, 185, 80, 0.14)',
  warning: '#d29922',
  warningSoft: 'rgba(210, 153, 34, 0.16)',
  error: '#f85149',
  errorSoft: 'rgba(248, 81, 73, 0.14)',
  purple: '#a78bfa',
  purpleSoft: 'rgba(167, 139, 250, 0.14)',
  blue: '#5aa9e6',
  blueSoft: 'rgba(90, 169, 230, 0.14)',
} as const

/** 供非 AntD 业务样式使用；挂在 documentElement 后也能覆盖 Portal。 */
export const themeCssVariables: Record<`--${string}`, string> = {
  '--bg': darkPalette.canvas,
  '--bg-soft': darkPalette.surfaceSubtle,
  '--panel': darkPalette.surface,
  '--panel-2': darkPalette.surfaceRaised,
  '--border': darkPalette.border,
  '--border-soft': darkPalette.borderSubtle,
  '--text': darkPalette.text,
  '--text-2': darkPalette.textSecondary,
  '--text-3': darkPalette.textTertiary,
  '--text-on-accent': darkPalette.textOnAccent,
  '--text-on-success': darkPalette.textOnSuccess,
  '--accent': darkPalette.primary,
  '--accent-hover': darkPalette.primaryHover,
  '--accent-active': darkPalette.primaryActive,
  '--accent-strong': darkPalette.primaryText,
  '--accent-soft': darkPalette.primarySoft,
  '--teal': darkPalette.success,
  '--teal-soft': darkPalette.successSoft,
  '--purple': darkPalette.purple,
  '--purple-soft': darkPalette.purpleSoft,
  '--blue': darkPalette.blue,
  '--blue-soft': darkPalette.blueSoft,
  '--amber': darkPalette.warning,
  '--amber-soft': darkPalette.warningSoft,
  '--red': darkPalette.error,
  '--red-soft': darkPalette.errorSoft,
}

export const themeTokens: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  cssVar: { key: 'audio-studio' },
  token: {
    colorPrimary: darkPalette.primary,
    colorPrimaryHover: darkPalette.primaryHover,
    colorPrimaryActive: darkPalette.primaryActive,
    colorInfo: darkPalette.primary,
    colorLink: darkPalette.primaryText,
    colorLinkHover: darkPalette.primaryText,
    colorSuccess: darkPalette.success,
    colorWarning: darkPalette.warning,
    colorError: darkPalette.error,
    colorBgBase: darkPalette.canvas,
    colorBgLayout: darkPalette.canvas,
    colorBgContainer: darkPalette.surface,
    colorBgElevated: darkPalette.surfaceRaised,
    colorBgSpotlight: darkPalette.surfaceRaised,
    colorBorder: darkPalette.border,
    colorBorderSecondary: darkPalette.borderSubtle,
    colorText: darkPalette.text,
    colorTextSecondary: darkPalette.textSecondary,
    colorTextTertiary: darkPalette.textTertiary,
    borderRadius: 6,
    fontSize: 14,
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.32)',
    boxShadowSecondary: '0 12px 32px rgba(0, 0, 0, 0.4)',
  },
  components: {
    Layout: {
      siderBg: darkPalette.surfaceUnder,
      headerBg: darkPalette.surfaceSubtle,
      bodyBg: darkPalette.canvas,
    },
    Menu: {
      darkItemBg: 'transparent',
      darkSubMenuItemBg: 'transparent',
      darkItemColor: darkPalette.textSecondary,
      darkItemHoverColor: darkPalette.text,
      darkItemSelectedColor: darkPalette.primaryText,
      darkItemSelectedBg: darkPalette.primarySoft,
    },
    Card: {
      colorBgContainer: darkPalette.surface,
    },
    Button: {
      colorPrimary: darkPalette.primary,
      colorPrimaryHover: darkPalette.primaryHover,
      colorPrimaryActive: darkPalette.primaryActive,
      primaryColor: darkPalette.textOnAccent,
      primaryShadow: 'none',
    },
    Tabs: {
      inkBarColor: darkPalette.primary,
      itemActiveColor: darkPalette.primary,
      itemHoverColor: darkPalette.primaryText,
      itemSelectedColor: darkPalette.primaryText,
    },
    Slider: {
      trackBg: darkPalette.primary,
      trackHoverBg: darkPalette.primaryHover,
      handleColor: darkPalette.primaryText,
      handleActiveColor: darkPalette.primaryText,
    },
    Progress: {
      defaultColor: darkPalette.primary,
    },
    Radio: {
      colorPrimary: darkPalette.primary,
      colorPrimaryHover: darkPalette.primaryHover,
      colorPrimaryActive: darkPalette.primaryActive,
    },
    Switch: {
      colorPrimary: darkPalette.primary,
      colorPrimaryHover: darkPalette.primaryHover,
    },
    Checkbox: {
      colorPrimary: darkPalette.primary,
      colorPrimaryHover: darkPalette.primaryHover,
    },
  },
}
